version: "3.4"

services:
  portainer:
    image: "{{portainer_image}}"
    command: --admin-password '{{vault_portainer_root_password}}' --host 'unix:///var/run/docker.sock'
    ports:
      - "{{portainer_tcp_port}}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #http://portainer.readthedocs.io/en/stable/deployment.html#persist-portainer-data
      - {{docker_containers_volume_path}}/portainer/data:/data
    deploy:
{% if portainer_mode is defined %}{% if portainer_mode[0] == 'replicated' %}
      replicas: {{portainer_mode[1]|default("1")}}
{% else %}
      mode: global
{% endif %}{% endif %}
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host: {% for subdomain in portainer_subdomains %}{{subdomain}}.{{domain}}, {% endfor %}"
        - "traefik.docker.network=traefik_external"
        - "traefik.port=9000"
    networks:
      - traefik_external
    logging:
      driver: syslog
      options:
        syslog-facility: local2 #as defined at roles/docker/templates/rsyslog.docker.conf
        tag: "docker/{% raw %}{{.Name}}{% endraw %}"

networks:
  traefik_external:
    external: true
